### PR TITLE
Update your-first-program.html

### PR DESCRIPTION
**Pull request by Walkman100**
http://www.quickanddirtytips.com/education/grammar/ado-versus-adieu
Spelling fixes.

### CODE REVIEW

**Comment by deavmi** [comment]
@Walkman100 Is it ado then?

**Comment by deavmi** [comment]
Unnecessary changes were made, only `ado` was needed.

**Comment by Walkman100** [comment]
Dude...

**Comment by Walkman100** [comment]
I fixed spelling, which includes ado

**Comment by deavmi** [comment]
Were other spelling fixes made?

**Comment by deavmi** [comment]
besides ado?

**Comment by Walkman100** [comment]
three things:
`a due` -> `ado`
`of` -> `off` (second line)
`follwoing` -> `following` (in the last few words on the page)

**Comment by deavmi** [comment]
Also when checking the documentation, do spelling fixes on the `docs` repo not this one. I know I did send you a link to the github pages. This repo contains the site and online documentation which is deprecated very quickly until I update it.

**Comment by deavmi** [comment]
@Walkman100 okay, lets me update the cos then.

**Comment by Walkman100** [comment]
I looked in the readme, there was no reference to a docs or source repo, so I just updated it directly

**Comment by deavmi** [comment]
Done

**Comment by deavmi** [comment]
@Walkman100 thanks. :) It was hard to see changes with no word wrap in the diff viewer.

**Comment by Walkman100** [comment]
Yeah, and it doesn't show changes highlighted like it usually does

**Comment by deavmi** [comment]
Really? Jeese, don't you use reviewable?

**Comment by Walkman100** [comment]
What

**Comment by deavmi** [comment]
Reviewable.io, they can do diffs for PRs right?

**Pull request closed without merging**
